export const types = {
  HANDLE_CHANGE: "HANDLE_CHANGE",
  INIT_IMAGE: "INIT_IMAGE",
  SELECT_TOOL: "SELECT_TOOL",
  STORE_TOOL_PARAMETERS: "STORE_TOOL_PARAMETERS",
  STORE_PARAMETERS: "STORE_PARAMETERS",
  ADD_OPERATION: "ADD_OPERATION",
  REMOVE_OPERATION: "REMOVE_OPERATION",
  ADD_EFFECT: "ADD_EFFECT",
  REMOVE_EFFECT: "REMOVE_EFFECT",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ALL_ITEM: "REMOVE_ALL_ITEM"
};
