export const types = {
  HANDLE_CHANGE: "HANDLE_CHANGE",
  INIT_IMAGE: "INIT_IMAGE",
  SELECT_TOOL: "SELECT_TOOL",
  STORE_PARAMETERS: "STORE_PARAMETERS",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ALL_ITEM: "REMOVE_ALL_ITEM"
};
