export const types = {
  SET_RECTANGLE: "SET_RECTANGLE",
  GET_GROUND: "GET_GROUND",
  GET_GROUND_SUCCESS: "GET_GROUND_SUCCESS",
  GET_GROUND_FAILED: "GET_GROUND_FAILED",
  GET_GROUND_LOADING: "GET_GROUND_LOADING"
};

export const urls = {
  estimate: "/estimate/"
};
